### ISSUE TITLE
header is the only thing showing up

### ISSUE THREAD

**Issue by kflick418** [ryck/MMM-Humanize-Duration#2]
I cannot get the clock to show up. A simple copy paste of the default code listed does not even work. Header will only show up with "David".

**Comment by ryck** [comment]
Hi!

I just tested the default code again (just in case) and it's working for me...

1. Is this the only module that doesn't work?
2. Are you getting any error in the console?
3. Are you using the latest MagicMirror version?
4. Is your config.json valid?

This is the config  I use right now, and it's working:

`		
{
			module: "MMM-Humanize-Duration",
			position: "bottom_left",
			header: "🍼David",
			config: {
				date: "2018-11-01 07:51",
				options: {
					units: ["y", "mo", "w", "d"],
					round: true,
					largest: 3,
				},
				updateInterval: 1 * 1 * 1000,
				animationSpeed: 250,
				initialLoadDelay: 0,
				debug: false
			}
		},
`

**Comment by kflick418** [comment]
1. This is the only module that's not working. I just started adding modules and this is my first mirror so I've had issues with a few of the more complex ones, but I think that's just my errors.

2. Theres no errors that are showing up. It is literally just the name and then the line for the header. I thought it was just me while changing the dates but I added your code only without making changes and it did the same.

3. I believe it is the latest version. I just loaded it within the last week.

4. I dont know how to check that the config.json is valid. Are you able to coach me through that?

I would imagine it's a very simple reason why it's not working since it's only a few lines not coming up. Does it matter what region I put it in? 

Here is a copy of what I have.

{
	module: 'MMM-Humanize-Duration',
	position: 'bottom_left',
	header: 'David',
	config: {
		date: "2018-11-01 07:51",
		options: {
			units: ["y", "mo", "w", "d", "h", "m", "s"],
			round: true,
			largest: 3,
		},
		updateInterval: 1 * 1 * 1000,
		animationSpeed: 250,
		initialLoadDelay: 0,
		debug: false
	}
},

**Comment by ryck** [comment]
To be honest, I don't know either what's going on... The plugin is as simple as you can get, so I'm not sure what is happening...
I guess you installed the plugin, `npm install` and all that, right?

Can you check the console to see what's going on?

**Comment by kflick418** [comment]
Ok, so i dont know what i did different the 2nd time around but i deleted everything with the module and re-installed. Works like a charm this time around. Thank you for your help and for creating this module!

**Comment by ryck** [comment]
I'm happy you made it work!
